# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wl < Formula
  desc "WireLog CLI — headless analytics for agents and LLMs"
  homepage "https://wirelog.ai"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.2.0/wl_0.2.0_darwin_amd64.tar.gz"
      sha256 "097c6415c44a2a1520c4f35bcd92ec75222b9e9c0e47e8fa7f9076089f761459"

      define_method(:install) do
        bin.install "wl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.2.0/wl_0.2.0_darwin_arm64.tar.gz"
      sha256 "e4d34571929f02a4c5c83a2574ff9e41e3cd23173ba2fdaa819b69432d09892f"

      define_method(:install) do
        bin.install "wl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.2.0/wl_0.2.0_linux_amd64.tar.gz"
      sha256 "f9f2fc734c02a5e3f90d3d3716c9f514ad743f22bed65989162b99cfcbc06c18"
      define_method(:install) do
        bin.install "wl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.2.0/wl_0.2.0_linux_arm64.tar.gz"
      sha256 "61311850516ac9463de57a3e14688400df5954e21363afaccf7302bfd552026b"
      define_method(:install) do
        bin.install "wl"
      end
    end
  end

  test do
    system bin/"wl", "version"
  end
end
