# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wl < Formula
  desc "WireLog CLI — headless analytics for agents and LLMs"
  homepage "https://wirelog.ai"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.4.0/wl_0.4.0_darwin_amd64.tar.gz"
      sha256 "7215686ffea6366437bf916c831ad7396538a1b467f7894287729798bc189d3e"

      define_method(:install) do
        bin.install "wl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.4.0/wl_0.4.0_darwin_arm64.tar.gz"
      sha256 "0f79d96b85844e0c0f802e7fc05c2ce4884b4c533fe1e0a275ecf9d6a308ab37"

      define_method(:install) do
        bin.install "wl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.4.0/wl_0.4.0_linux_amd64.tar.gz"
      sha256 "d135011e244881df6abcc09238a7547ef5e3af10de0daf8aebce2bd2524a57f1"
      define_method(:install) do
        bin.install "wl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wirelogai/wirelog-cli/releases/download/v0.4.0/wl_0.4.0_linux_arm64.tar.gz"
      sha256 "06e5837d47dd54fd7782b5e16ad77624d0c9fcb696071c82cd34aec6372a9079"
      define_method(:install) do
        bin.install "wl"
      end
    end
  end

  test do
    system bin/"wl", "version"
  end
end
